source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'spring',      group: :development

# Flapper Germs
gem 'angular-rails-templates'
# gem 'responders', '~> 2.0'
gem 'angular_rails_csrf'
# gem 'sprockets', '2.12.3'

gem 'devise', '~> 3.4.0'

